import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { log } from './lib/log.js'

/**
 * Access control + per-user wallet keys, in one JSON file (data/accounts.json).
 *
 * Admins (from env) are always allowed and can grant/revoke other Telegram ids.
 * Each user's wallet is a NEAR account id + its private key, stored only
 * AES-256-GCM encrypted — the raw key is never written to disk or logs.
 */

export interface AllowEntry {
  addedBy: number
  addedAt: string
  note?: string
}

export interface KeyRecord {
  accountId: string
  publicKey: string
  /** How the wallet got here: generated by the bot, or imported by the user. */
  source: 'created' | 'imported'
  /** Encrypted private key (AES-256-GCM). */
  enc: string
  updatedAt: string
}

interface Data {
  allowed: Record<string, AllowEntry>
  keys: Record<string, KeyRecord>
}

const empty = (): Data => ({ allowed: {}, keys: {} })

export class Accounts {
  private readonly data: Data
  private readonly file: string

  constructor(dataDir: string) {
    mkdirSync(dataDir, { recursive: true })
    this.file = join(dataDir, 'accounts.json')
    try {
      const raw = JSON.parse(readFileSync(this.file, 'utf8')) as Partial<Data>
      this.data = { allowed: raw.allowed ?? {}, keys: raw.keys ?? {} }
    } catch {
      this.data = empty()
    }
  }

  private save(): void {
    const tmp = `${this.file}.tmp`
    try {
      writeFileSync(tmp, JSON.stringify(this.data, null, 2))
      renameSync(tmp, this.file) // atomic swap
    } catch (err) {
      log.error('failed to save accounts', err)
    }
  }

  // ---- access list ----

  isAllowed(id: number): boolean {
    return Boolean(this.data.allowed[String(id)])
  }
  allow(id: number, addedBy: number, note?: string): void {
    this.data.allowed[String(id)] = { addedBy, addedAt: new Date().toISOString(), note }
    this.save()
  }
  disallow(id: number): void {
    delete this.data.allowed[String(id)]
    delete this.data.keys[String(id)] // revoking access also drops the stored key
    this.save()
  }
  listAllowed(): Array<[number, AllowEntry]> {
    return Object.entries(this.data.allowed).map(([id, e]) => [Number(id), e])
  }

  // ---- key records ----

  setKey(id: number, rec: KeyRecord): void {
    this.data.keys[String(id)] = rec
    this.save()
  }
  getKey(id: number): KeyRecord | undefined {
    return this.data.keys[String(id)]
  }
  clearKey(id: number): void {
    delete this.data.keys[String(id)]
    this.save()
  }
}
